async/await 的优雅处理
```javascript
 async function foo() {
    try {
        await fn()
    } catch(error) {
        // 此处能捕捉到error的信息
    }
 } 

 fn() {
    return Promise.reject('xxx')
 }
```